project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    right:
      - text: Home
        href: index.qmd
      
format:
  html:
    theme: [cosmo, styles.scss]

